---
title: "ShinyProject"
author: "spidy001"
date: "January 26, 2016"
output: ioslides_presentation
runtime: shiny
---

## Shiny Presentation

This R Markdown presentation is made interactive using Shiny. The viewers of the presentation can change the assumptions underlying what's presented and see the results immediately. 

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

## Slide with Interactive Plot

```{r, echo=FALSE}
library(shiny)
shinyUI(
        pageWithSidebar(
                # Application title
                headerPanel("Yellowstone Old Faithful Geyser Eruption time Prediction"),
                sidebarPanel(
                        numericInput('wait', 
                                     'Enter geyser waiting time',
                                     80 , min = 45, max = 5000, step = 1),
                        selectInput("waitingTimeUnit", "Units:",
                                    c("Minutes" = "Minutes",
                                      "Seconds" = "Seconds")),
                        submitButton('Submit')
                ),
                mainPanel(
                        h3('Results of prediction'),
                        h4('You entered a geyser waiting time of '),
                        verbatimTextOutput("inputValue"),
                        h4('Which resulted in a prediction of (in minutes) '),
                        verbatimTextOutput("prediction")
                        
                )
        )
)

```

```{r,echo = TRUE}

```

```{r,echo=FALSE}
eruptionPredictor <- function(wait) {
        eruptionsLinearModel <- lm(eruptions ~ waiting,data= faithful)
        newdata = data.frame(waiting=wait)
        predict(eruptionsLinearModel, newdata) 
}
shinyServer(
        function(input, output) {
                output$inputValue <- renderPrint(
                        paste(input$wait," ",input$waitingTimeUnit))
        waitingTime <- reactive({
                if(input$waitingTimeUnit == "Seconds")
                         input$wait / 60
                else
                {
                         input$wait
                } 
        })
                        
        output$prediction <- renderPrint({eruptionPredictor(waitingTime())})
        })
```

## Slide with Bullets
- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Code and Output

```{r}
summary(faithful)
```


